// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tpunvbnfmmrnyiduyqwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwdW52Ym5mbW1ybnlpZHV5cXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTkwNTYsImV4cCI6MjA2OTg3NTA1Nn0.dydbp2mbdUzb8rprRyk4o0gdpFfC0VmgnvcIJS2aSXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);